import { BuildingDto } from "./building.dto"
import { DecoDto } from "./deco.dto"
import { DragonDto } from "./dragon.dto"

export interface RestructuredItemsDto {
    buildings: Array<BuildingDto>
    boosters: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {
            g: number
        }
        display_order: number
        boost_modifier: {
            p?: number
            e?: number
            f?: number
            i?: number
            el?: number
            w?: number
            d?: number
            l?: number
            m?: number
            pu?: number
            li?: number
            pr?: number
            wd?: number
            wr?: number
        }
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: string
        velocity: number
        description: string
        sell_price: {
            g: number
        }
        properties: {
            bulldozable: number
            range: number
        }
        building_ownership_id: number
    }>
    farms: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {
            g: number
        }
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: string
        velocity: number
        description: string
        sell_price: {
            g: number
        }
        properties: {
            multiCollectable: number
            friend_assistable: number
            upgrade_from?: number
        }
        building_ownership_id: number
    }>
    decos: Array<DecoDto>
    habitats: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        elements: Array<string>
        xp: number
        min_level: number
        costs: {
            g?: number
            e_token?: number
            f_token?: number
            w_token?: number
            p_token?: number
            el_token?: number
            i_token?: number
            m_token?: number
            d_token?: number
            li_token?: number
            wr_token?: number
            pu_token?: number
            l_token?: number
            pr_token?: number
            wd_token?: number
            n_token?: number
        }
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: string
        velocity: number
        description?: string
        sell_price: {
            g: number
        }
        multiple_costs?: Array<{
            g?: number
            d_token?: number
            pu_token?: number
        }>
        properties: {
            habitat: number
            capacity: number
            bulldozable?: number
            friend_assistable: number
            max_gold: number
            upgrade_from?: number
            habitat_pure?: number
            fixed_position?: Array<number>
            is_fixed?: number
        }
        building_ownership_id: number
    }>
    obstacles: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type?: string
        xp: number
        min_level: number
        costs: {
            g: number
        }
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: string
        velocity?: number
        properties: {
            bulldozable: number
        }
        building_ownership_id: number
        description?: string
    }>
    lands: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {
            g: number
        }
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: string
        sell_price: {
            g: number
        }
        building_ownership_id: number
    }>
    social_buildings: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        xp: number
        min_level: number
        costs: {
            g: number
        }
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        velocity: number
        description: string
        sell_price: {
            g: number
        }
        properties: {
            bulldozable: number
        }
        building_ownership_id: number
    }>
    kindergartens: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        elements: Array<string>
        xp: number
        min_level: number
        costs: {
            c?: number
            kg_token?: number
        }
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: string
        velocity: number
        description: string
        sell_price: {
            g: number
        }
        multiple_costs?: Array<{
            c: number
        }>
        costs_array?: Array<{
            c: number
        }>
        sell_price_array?: Array<{
            g: number
        }>
        multiple_sell_prices?: Array<{
            g: number
        }>
        properties: {
            habitat: number
            capacity: number
            bulldozable: number
            friend_assistable: number
            max_gold: number
            upgrade_from?: number
        }
        building_ownership_id: number
    }>
    lostitems: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {}
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: string
        velocity: number
        properties: {
            bulldozable: number
            lost_item: number
        }
        building_ownership_id: number
    }>
    crosspromotions: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {}
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: string
        velocity: number
        properties: {
            floating: number
            bulldozable: number
            crosspromotion: number
        }
        building_ownership_id: number
    }>
    promoislands: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {}
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: string
        velocity: number
        sell_price: {}
        properties: {
            floating: number
            bulldozable: number
            crosspromotion: number
        }
        building_ownership_id: number
    }>
    collectislands: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {}
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: string
        velocity: number
        sell_price: {}
        properties: {
            floating: number
            bulldozable: number
            crosspromotion: number
        }
        building_ownership_id: number
    }>
    dragonariums: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {
            g: number
        }
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: string
        velocity: number
        description: string
        sell_price: {}
        properties: {
            habitat: number
            capacity: number
            bulldozable: number
            workingBuilding: number
        }
        building_ownership_id: number
    }>
    atrezzos: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {}
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: string
        velocity: number
        description: string
        sell_price: {}
        properties: {
            floating: number
            fixed_position: Array<number>
            is_fixed: number
        }
        building_ownership_id: number
    }>
    mistery_eggs: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {}
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: string
        velocity: number
        properties: {
            bulldozable: number
            lost_item: number
        }
        building_ownership_id: number
    }>
    promos: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {
            g: number
        }
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: string
        velocity: number
        description: string
        sell_price: {
            g: number
        }
        properties: {
            bulldozable: number
            workingBuilding: number
            fixed_position: Array<number>
            is_fixed: number
        }
        building_ownership_id: number
    }>
    units: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {
            g: number
        }
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: string
        velocity: number
        sell_price: {
            g: number
        }
        properties: {
            workingBuilding: number
            ft_flying: number
        }
        building_ownership_id: number
    }>
    popups: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {
            g: number
        }
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: string
        velocity: number
        sell_price: {
            g: number
        }
        properties: {
            workingBuilding: number
            ft_flying: number
        }
        building_ownership_id: number
        description?: string
    }>
    deusislands: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {}
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: number
        velocity: number
        description: string
        sell_price: {}
        properties: {
            floating: number
            bulldozable: number
        }
        building_ownership_id: number
    }>
    chestcontainers: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        elements: Array<string>
        xp: number
        min_level: number
        costs: {}
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: string
        velocity: number
        description: string
        sell_price: {}
        properties: {
            habitat: number
            capacity: number
            bulldozable: number
            friend_assistable: number
            max_gold: number
        }
        building_ownership_id: number
    }>
    halloween_islands: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {}
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: number
        velocity: number
        description: string
        sell_price: {}
        properties: {
            floating: number
            bulldozable: number
            crosspromotion: number
        }
        building_ownership_id: number
    }>
    dwportals: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {}
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: string
        description: string
        sell_price: {}
        properties: {
            bulldozable: number
            friend_assistable: number
        }
        building_ownership_id: number
    }>
    progressive_islands: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {}
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: number
        velocity: number
        description: string
        sell_price: {}
        properties: {
            floating: number
            bulldozable: number
            crosspromotion: number
            fixed_position?: Array<number>
        }
        building_ownership_id: number
    }>
    meme_generators: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {
            g: number
        }
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: number
        velocity: number
        description: string
        sell_price: {
            g: number
        }
        properties: {
            floating: number
            bulldozable: number
        }
        building_ownership_id: number
    }>
    mage_shrines: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {
            c: number
        }
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: number
        velocity: number
        description: string
        sell_price: {
            g: number
        }
        properties: {
            floating: number
            bulldozable: number
            required_items?: Array<number>
        }
        building_ownership_id: number
    }>
    gd_towers: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {
            c: number
        }
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: string
        velocity: number
        description: string
        properties: {
            bulldozable: number
            workingBuilding: number
        }
        building_ownership_id: number
    }>
    grid_islands: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: any
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: number
        velocity: number
        description?: string
        sell_price: any
        properties: {
            floating: number
            bulldozable: number
            crosspromotion?: number
            fixed_position?: Array<number>
            lost_item?: number
        }
        building_ownership_id: number
    }>
    cum_calendar_islands: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {}
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: number
        velocity: number
        description: string
        sell_price: {}
        properties: {
            floating: number
            bulldozable: number
            crosspromotion: number
        }
        building_ownership_id: number
    }>
    trader_islands: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {}
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: number
        velocity: number
        description: string
        sell_price: {}
        properties: {
            floating: number
            bulldozable: number
            crosspromotion: number
        }
        building_ownership_id: number
    }>
    dragon_cinemas: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {}
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: number
        velocity: number
        description?: string
        sell_price: {}
        properties: {
            floating: number
            bulldozable: number
            crosspromotion: number
        }
        building_ownership_id: number
    }>
    fog_islands: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {}
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: number
        velocity: number
        description?: string
        sell_price: {}
        properties: {
            floating: number
            bulldozable?: number
            crosspromotion?: number
            fixed_position?: Array<number>
            lost_item?: number
        }
        building_ownership_id: number
        scale?: number
    }>
    heroic_races: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {}
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: number
        velocity: number
        description: string
        sell_price: {}
        properties: {
            floating: number
            bulldozable: number
            crosspromotion?: number
        }
        building_ownership_id: number
        scale?: number
    }>
    maze_islands: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {}
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: number
        velocity: number
        description?: string
        sell_price: {}
        properties: {
            floating: number
            bulldozable: number
            crosspromotion: number
            fixed_position?: Array<number>
        }
        building_ownership_id: number
    }>
    tower_islands: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {}
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: number
        velocity: number
        description: string
        sell_price: {}
        properties: {
            floating: number
            bulldozable: number
            crosspromotion: number
            fixed_position?: Array<number>
        }
        building_ownership_id: number
    }>
    event_islands: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {}
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: number
        velocity: number
        sell_price: {}
        properties: {
            floating: number
            bulldozable: number
            crosspromotion: number
            fixed_position: Array<number>
        }
        building_ownership_id: number
        description?: string
    }>
    tree_of_lives: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {}
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: number
        velocity: number
        description: string
        sell_price: {}
        properties: {
            floating: number
            fixed_position: Array<number>
        }
        building_ownership_id: number
    }>
    alliance_portals: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {}
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: string
        description: string
        sell_price: {}
        properties: {
            bulldozable: number
            friend_assistable: number
        }
        building_ownership_id: number
    }>
    burrows: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {
            g: number
        }
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: string
        velocity: number
        description: string
        sell_price: {}
        properties: {
            bulldozable: number
            max_dragon_level: number
            upgrade_from?: number
        }
        building_ownership_id: number
    }>
    alliance_races: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {}
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: number
        velocity: number
        description: string
        sell_price: {}
        properties: {
            floating: number
            bulldozable: number
            crosspromotion: number
        }
        building_ownership_id: number
    }>
    collectibles: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {
            c: number
        }
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: string
        velocity: number
        description: string
        sell_price: {
            g: number
        }
        properties: {
            bulldozable: number
        }
        building_ownership_id: number
    }>
    greenhouses: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {
            g: number
        }
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: any
        velocity: number
        description: string
        sell_price: {
            g: number
        }
        properties: {
            bulldozable?: number
            workingBuilding: number
            floating?: number
        }
        building_ownership_id: number
    }>
    puzzle_islands: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {}
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: number
        velocity: number
        description?: string
        sell_price: {}
        properties: {
            floating: number
            bulldozable: number
            crosspromotion?: number
            fixed_position?: Array<number>
        }
        building_ownership_id: number
        scale?: number
    }>
    breeding_islands: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {}
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: string
        velocity: number
        description: string
        properties: {
            floating: number
            workingBuilding: number
            fixed_position: Array<number>
        }
        building_ownership_id: number
    }>
    dragon_obstacles: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {}
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: string
        velocity: number
        description: string
        sell_price: {
            g: number
        }
        properties: {
            bulldozable: number
        }
        building_ownership_id: number
    }>
    runner_islands: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {}
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: number
        velocity: number
        description: string
        sell_price: {}
        properties: {
            floating: number
            bulldozable: number
        }
        building_ownership_id: number
    }>
    dragon_tvs: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {}
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: number
        velocity: number
        description: string
        sell_price: {}
        properties: {
            floating: number
            bulldozable: number
            crosspromotion: number
        }
        building_ownership_id: number
    }>
    offerwalls: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {}
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: number
        velocity: number
        description: string
        sell_price: {}
        properties: {
            floating: number
            bulldozable: number
            crosspromotion: number
        }
        building_ownership_id: number
    }>
    orb_habitats: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        elements: Array<string>
        xp: number
        min_level: number
        costs: {
            oph_token?: number
        }
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: string
        velocity: number
        description: string
        sell_price: {}
        properties: {
            habitat: number
            capacity: number
            friend_assistable: number
            max_gold: number
            upgrade_from?: number
        }
        building_ownership_id: number
    }>
    wizards_caves: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {}
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: number
        velocity: number
        description: string
        sell_price: {}
        properties: {
            floating: number
            bulldozable: number
            crosspromotion: number
            fixed_position: Array<number>
        }
        building_ownership_id: number
    }>
    teaser_islands: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {}
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: number
        velocity: number
        description: string
        sell_price: {}
        properties: {
            floating: number
            bulldozable: number
            crosspromotion: number
        }
        building_ownership_id: number
    }>
    brand_decos: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        deco_seg_id: number
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {
            c: number
        }
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: string
        velocity: number
        description: string
        sell_price: {
            g: number
        }
        properties: {
            bulldozable: number
        }
        building_ownership_id: number
    }>
    collectors_hunts: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {}
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: number
        velocity: number
        description: string
        sell_price: {}
        properties: {
            floating: number
            bulldozable: number
            crosspromotion: number
            fixed_position: Array<number>
        }
        building_ownership_id: number
    }>
    dragon_pets: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: {}
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        activation: number
        upgrades_to: number
        collect_type: number
        velocity: number
        description: string
        sell_price: {}
        properties: {
            floating: number
            bulldozable: number
            crosspromotion: number
            fixed_position: Array<number>
        }
        building_ownership_id: number
    }>
    dragon_trails: Array<{
        id: number
        name: string
        group_type: string
        name_key?: string
        animated: number
        build_time: number
        mobile_version: number
        android_version: number
        show_on_mobile: number
        type: string
        element_type: string
        xp: number
        min_level: number
        costs: Array<any>
        display_order: number
        boost_modifier: number
        gift_level: number
        giftable: number
        cost_unit_cash: number
        collect: number
        collect_xp: number
        category_id: number
        subcategory_id: number
        building_limit_same_id: number
        in_store: number
        width: number
        height: number
        new_item: number
        img_name: string
        img_name_mobile: string
        img_name_android: string
        scale: number
        activation: number
        upgrades_to: number
        collect_type: number
        velocity: number
        description: string
        sell_price: Array<any>
        properties: {
            floating: number
            bulldozable: number
            crosspromotion: number
        }
        building_ownership_id: number
    }>
    dragons: Array<DragonDto>
}
