import path from "node:path"
import { z } from "zod"

export const gridIslandSchema = z.object({
    id: z.number(),
    analytics_id: z.string(),
    tid_name: z.string(),
    tutorial_id: z.number(),
    tutorial_claimable_cell_id: z.number(),
    pool_points: z.number(),
    pool_time: z.number(),
    initial_points: z.number(),
    start_ts: z.number(),
    end_ts: z.number(),
    currency_id: z.number(),
    min_level: z.number(),
    building_id: z.number(),
    building_position: z.array(z.number()),
    zip_file: z.string(),
    sound_tag: z.string(),
    canvas_assets_url: z.string(),
    ui_configuration: z.object({
        cell_contents_config: z.object({
            blocked_dragon_position_offset: z.array(z.number()),
            blocked_opacity: z.number(),
            claimable_dragon_position_offset: z.array(z.number()),
            default_dragon_scale: z.array(z.number()),
            dragon_scale: z.array(z.number()),
            dragon_scale_by_id: z.record(z.number(), z.array(z.number())),
            icon_position_offset: z.array(z.number()),
            label_position_offset: z.array(z.number()),
        }),
        cell_highlight_asset: z.string(),
        cell_highlight_index: z.number(),
        cell_size: z.array(z.number()),
        cells_label_config: z.object({
            claimable: z.object({
                color: z.array(z.number()),
                size: z.number(),
                stroke_color: z.array(z.number()),
                stroke_width: z.number(),
            }),
            unclaimable: z.object({
                color: z.array(z.number()),
                size: z.number(),
                stroke_color: z.array(z.number()),
                stroke_width: z.number(),
            }),
        }),
        dragon_evolution: z.number(),
        grey_scale_blocked_cells: z.boolean(),
        island_title_config: z.object({
            down_color: z.array(z.number()),
            size: z.number(),
            small_stroke_color: z.array(z.number()),
            small_stroke_width: z.number(),
            upper_color: z.array(z.number()),
        }),
        layers_z_indexes: z.object({
            additional_layer: z.number(),
            cell_backgrounds: z.number(),
            cell_contents: z.number(),
            decorations: z.number(),
            player_token: z.number(),
            walls: z.number(),
        }),
        origin_offset: z.array(z.number()),
        tutorial_scroll_duration: z.number(),
        tutorial_scroll_duration_base: z.number(),
        tutorial_scroll_duration_factor: z.number(),
    }),
    active_platforms: z.object({
        ios: z.number(),
        canvas: z.string(),
        android: z.number(),
        amazon: z.number(),
        windows: z.number(),
    }),
    episodes: z.array(z.number()),
    board_size: z.array(z.number()),
    initial_square_id: z.number(),
    backgrounds: z.array(z.number()),
    background_plist: z.string(),
    foregrounds: z.array(z.any()),
    foregrounds_plists: z.array(z.any()),
}).strict().transform(data => {
    return {
        id: data.id,
        min_level: data.min_level,
        availability: {
            from: new Date(data.start_ts * 1000).toISOString(),
            to: new Date(data.end_ts * 1000).toISOString(),
        },
        name_key: data.tid_name,
        sound_tag: data.sound_tag,
        zip_file_name: path.basename(data.zip_file),
        currency_id: data.currency_id,
        pool: {
            points: data.pool_points,
            time: data.pool_time,
        },
        initial_points: data.initial_points,
        board_size: {
            width: data.board_size[0],
            height: data.board_size[1],
        },
        initial_square_id: data.initial_square_id,
        episode_ids: data.episodes,
    }
})