import path from "node:path"
import { z } from "zod"

import { numberToBoolean } from "../../../utils"

export const heroicRacesIslandSchema = z.object({
    id: z.number(),
    active_platforms: z.object({
        ios: z.array(z.number()),
        android: z.array(z.number()),
        amazon: z.array(z.number()),
        windows: z.array(z.number()),
        canvas: z.array(z.number()),
    }),
    min_level: z.number(),
    start_ts: z.number(),
    end_ts: z.number(),
    end_ts_threshold: z.number(),
    secs_before_cache_freeze: z.number(),
    min_qualifying_laps: z.number(),
    laps: z.array(z.number()),
    building_id: z.number(),
    building_id_96: z.number(),
    building_claim_id: z.number(),
    building_free_spin_id: z.number(),
    building_position: z.array(z.number()),
    dragon_building_position: z.array(z.number()),
    dragon_building_scale: z.number(),
    zip_file: z.string(),
    canvas_assets_url: z.string(),
    island_title_tid: z.string(),
    sound_tag: z.string(),
    level_tiers: z.array(z.number()),
    rewards: z.array(z.number()),
    dragon_race_id: z.number(),
    dragon_race_scale: z.number(),
    dragon_race_offset: z.array(z.number()),
    dragon_reward_scale: z.number(),
    dragon_reward_offset: z.array(z.number()),
    help_id: z.number(),
    dragon_is_new: z.number(),
    spinner_enabled: z.number(),
    spin_rewards: z.array(z.number()),
    spin_cooldown: z.number(),
    buy_spin_price: z.number(),
    notification_anim_remaining_time: z.number(),
    notification_anim_per_day: z.number(),
    notification_anim_duration: z.number(),
    lap_completed_to_hide_notification: z.number(),
}).strict().transform(data => {
    return {
        id: data.id,
        min_level: data.min_level,
        availability: {
            from: new Date(data.start_ts * 1000).toISOString(),
            to: new Date(data.end_ts * 1000).toISOString(),
            to_threshold: data.end_ts_threshold,
        },
        name_key: data.island_title_tid,
        sound_tag: data.sound_tag,
        zip_file_name: path.basename(data.zip_file),
        min_qualifying_laps: data.min_qualifying_laps,
        lap_ids: data.laps,
        level_tier_ids: data.level_tiers,
        reward_ids: data.rewards,
        race: {
            dragon_id: data.dragon_race_id,
            dragon_is_new: numberToBoolean(data.dragon_is_new),
        },
        spinner_enabled: data.spinner_enabled,
        spin_cooldown: data.spin_cooldown,
        spin_rewards: data.spin_rewards,
        buy_spin_price: data.buy_spin_price,
    }
})